version: '4'

services:
  bg1:
    image: gzy1/bg_basic
    environment:
      - LOCAL_NODE_NAME=node1
      - OTHER_NODE_1=node2
      - OTHER_NODE_2=node3
      - OTHER_NODE_3=node4
  bg2:
    image: gzy1/bg_basic
    environment:
      - LOCAL_NODE_NAME=node2
      - OTHER_NODE_1=node1
      - OTHER_NODE_2=node3
      - OTHER_NODE_3=node4
  bg3:
    image: gzy1/bg_basic
    environment:
      - LOCAL_NODE_NAME=node3
      - OTHER_NODE_1=node2
      - OTHER_NODE_2=node1
      - OTHER_NODE_3=node4
  bg4:
    image: gzy1/bg_basic
    environment:
      - LOCAL_NODE_NAME=node4
      - OTHER_NODE_1=node2
      - OTHER_NODE_2=node3
      - OTHER_NODE_3=node1

